version: '3'

services:
  database:
    build: ./database
    restart: always
    container_name: mariadb-docker
    image: database
    ports:
    - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
  app:
    build: ./springapp
    image: springapp
    container_name: iotspring-docker
    links:
      - database
    ports:
    - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/yurenia_db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - database
volumes:
  db-data: